package com.spike.commons.example.netty.userguide.echo;

import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;

import org.apache.log4j.Logger;

/**
 * EchoServer handler<br/>
 * responsibility: handle IO events generated by Netty
 * @see EchoServer
 */
public class EchoServerHandler extends ChannelInboundHandlerAdapter {
  private static final Logger LOG = Logger.getLogger(EchoServerHandler.class);

  /**
   * occurs when new data is received from a client
   */
  @Override
  public void channelRead(ChannelHandlerContext context, Object message) {
    // echo

    // 写入内部缓冲区中，并没有直接发送
    context.write(message);

    // 刷出缓冲区，发送消息
    context.flush();
  }

  /**
   * <pre>
   * occurs when exception raised by Netty due to IO error, or
   * due to handler's operation when processing events
   * 
   * 在Netty抛出IO异常或者handler处理事件操作中抛出异常时触发
   * 
   * </pre>
   */
  @Override
  public void exceptionCaught(ChannelHandlerContext context, Throwable cause) {
    // 记录日志
    if (cause != null) {
      // cause.printStackTrace();
      LOG.error(cause);
    }

    // 关闭channel
    LOG.info("关闭链接...");
    context.close();

    // 其他处理方式：根据异常类型处理，在关闭连接前发送响应消息等
  }
}
